# syntax=docker/dockerfile:1
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/service ./cmd/player

FROM alpine:3.20
RUN adduser -D -u 10001 app
USER app
COPY --from=build /out/service /service
EXPOSE 8081
ENTRYPOINT ["/service"]
